name: Branch Changes

on:
  push:
    branch:
      - '*'
      - '!main'

jobs:
  branches:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run check
      run: make check

    - name: Render site
      run: make build
