name: Run validation and build checks

on:
  workflow_dispatch:
  pull_request:
    types:
    - assigned
  push:
    branches:
      - '**'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run check
      run: make check


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Render site
      run: make build

    - name: Cached build
      uses: actions/cache@v4
      env:
        cache-name: build-output
      with:
        path: public/
        key: ${{ runner.os }}-${{ env.cache-name }}
