name: Run validation and build checks

on:
  pull_request:
    types:
    - assigned
    paths:
    - 'content/**'
    - 'static/**'
    - 'themes/**'
  push:
    branches:
      - '**'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run check
      run: make check


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Render site
      run: make build

    - name: Cached build
      uses: actions/cache@v2
      env:
        cache-name: build-output
      with:
        path: public/
        key: ${{ runner.os }}-${{ env.cache-name }}
