name: Checks

on:
  pull_request:
    types:
    - assigned
    paths:
    - 'content/**'
    - 'static/**'
    - 'themes/**'
  push:
    branches:
      - '**'
      - '!main'

jobs:
  checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run check
      run: make check

    - name: Render site
      run: make build

    steps:
    - name: Cached build
      uses: actions/cache@v2
      env:
        cache-name: build-output
      with:
        path: public/
        key: ${{ runner.os }}-${{ env.cache-name }}
